mobile_shop_app/config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items

  root to: "items#index"
  post 'items/new' ,to: "items#create"
  patch 'items/edit', to: "items#update"
end

mobile_shop_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

mobile_shop_app/app/models/item.rb
class Item < ApplicationRecord
	validates :name, presence: true
	validates :cost_price, presence: true
	#Item.create.errors[:name].any?
end

mobile_shop_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

mobile_shop_app/app/controllers/items_controller.rb
class ItemsController < ApplicationController
	

  def index
	@items = Item.all
  end

  def new
  	@item = Item.new
  end
  
  def show
  	@item = Item.find(params[:id] )
  end

  def destroy
  	@item = Item.find(params[:id])
  	if @item
  	  @item.destroy
  	  redirect_to items_path
  end
  end

  def update
  	@item = Item.find(params[:id])
  	if @item.update(params[:item].permit(:name, :stock, :cost_price))
  	  redirect_to items_path
  end
 end

  def create
  	@item = Item.new(name: params[:item][:name], stock: 0, cost_price: params[:item][:cost_price])
  	@item.save
  	if @item.save
  		redirect_to @item
  	else
      render action: 'new'
  	end
  end

  def edit
  	@item = Item.find(params[:id])
  end


end
  

mobile_shop_app/app/helpers/application_helper.rb
module ApplicationHelper
end

mobile_shop_app/app/views/items/edit.html.erb
<%= form_for @item do |e|%>
<table align="center" style="border: 2px solid black" cellpadding="5" cellspacing="20">
	<tr>
		<td>Item Name</td>
		<td><%= e.text_field :name%></td>
	</tr>
	<tr>
		<td>Stock</td>
		<td><%= e.text_field :stock%></td>
	</tr>
	<tr>
		<td>Cost Price</td>
		<td><%= e.text_field :cost_price%></td>
	</tr>

	<tr>
		<td></td>
		<td><%= e.submit "update" %></td>
	</tr>
</table>


<% end %>

<%= link_to 'Back', items_path %>

mobile_shop_app/app/views/items/index.html.erb
<p id="notice"> <%= notice %></p>
<table align="center">
	
	<thead>
		<tr>
			
			<th> Name</th>
			
		</tr>
	</thead>
	<tbody>
		<% @items.each do |item| %>
		<tr>
			
			<td><%= item.name %></td>
			
			<td><%= link_to "show", item %></td>
			<td><%= link_to 'Remove', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			<td><%= link_to "Edit",edit_item_path(item) %></td>
			
		</tr>
		<% end %>
	</tbody>
</table>
<td><%= link_to "Add New Item", new_item_path%></td>

mobile_shop_app/app/views/items/new.html.erb
<%= form_for :item do |e|%>
  
  


<table align="center" style="border: 2px solid black" cellpadding="5" cellspacing="20">
  <% if @item.errors.any? %>
        <div id="error_explanation">

          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this msg from being saved:</h2>

          <ul>
            <% @item.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
	<tr>
		<td>Item Name</td>
		<td><%= text_field :item, :name%></td>
	</tr>
	<tr>
		<td>Cost Price</td>
		<td><%= text_field :item, :cost_price%></td>
	</tr>
	<tr>
		<td></td>
		<td><%= e.submit %></td>
	</tr>
</table>


<% end %>

<%= link_to 'Back', items_path %>

mobile_shop_app/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Item Id  :  </strong>
	<%= @item.id%>
</p>

<p>
	<strong>Item Name  :  </strong>
	<%= @item.name%>
</p>

<p>
	<strong>Stock  :  </strong>
	<%= @item.stock%>
</p>

<p>
	<strong>Cost Price  :  </strong>
	<%= @item.cost_price%>
</p>

<td><%= link_to "back", items_path %></td>

mobile_shop_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MobileShopApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>